### ISSUE TITLE
Thumbnail of xenon: null

### ISSUE THREAD

**Issue by mamo5900** [satyakresna/bravefrontier#10]
Thumbnail of xenon: null, can you fix it? i retrieve the id of the unit from there and i have problems with it

**Comment by satyakresna** [comment]
Hi @mamo5900, thanks for reporting. It has been fixed. Here's the screenshot.

<img width="1552" alt="Screen Shot 2020-09-19 at 13 45 00" src="https://user-images.githubusercontent.com/11099186/93660127-59583e00-fa7e-11ea-8ad8-784befba0d58.png">

Please see on https://bfwiki.satyakresna.io. :)
Thanks.
