### ISSUE TITLE
problem with the search of builds for nimune and bjorn

### ISSUE THREAD

**Issue by mamo5900** [satyakresna/bravefrontier#11]
problem with the search of builds for nimune and bjorn, they have 2 characters  that aren't read from browser and api
[bjorn](https://bravefrontier.satyakresna.io/api/v1/omniunits/Cheery_Bj%C3%B8rn_&_Linlin)

**Comment by satyakresna** [comment]
Hi @mamo5900, if the unit name contains character like `&` then it must be encoded to get omni unit profile:

Example: `Cheery_Bjørn_&_Linlin` => `Cheery_Bjørn_%26_Linlin`.

https://bravefrontier.satyakresna.io/api/v1/omniunits/Cheery_Bjørn_%26_Linlin

Please kindly check the **Detail of Omni Unit** section:
https://github.com/satyakresna/bravefrontier#detail-of-omni-unit

Thank you.

**Comment by satyakresna** [comment]
I will close this issue.
