### ISSUE TITLE
Can you add a section in api v1 who show you also alter arts?

### ISSUE THREAD

**Issue by mamo5900** [satyakresna/bravefrontier#12]
Can you add a section in api v1 who show you also alter arts? For example Elaina has an alter Art, so i'd like to see an implementation about this

**Comment by satyakresna** [comment]
Hi @mamo5900, I'm sorry for a moment I don't have time to do that. If you can do this, you can fork this project and add alter arts implementation and then pull request to this repo. Thanks.
