### ISSUE TITLE
unit name parameter

### ISSUE THREAD

**Issue by mamo5900** [satyakresna/bravefrontier#6]
this api return only omni units so can you make we can use the firstname of a unit as parameter for the api? example: instead of Seiðkona_Aoife we can use only aoife or Aoife, you can use the "like" function and do a check on rarity if its rarity is 8

**Comment by mamo5900** [comment]
you can edit the code in this way 

const text = await fsPromises.readFile(file, 'utf-8');
    const omniUnits = JSON.parse(text);
    let selectedUnit = {};
    const unitName = name.split('_').join(' ').trim();
    for (let omniUnit of omniUnits) {
        if (omniUnit.name === name.split('_').join(' ').trim())
	if (contains(omniUnit.name, unitName) {
            selectedUnit = omniUnit;
        }
    }

and also update the file because today rené will be released

**Comment by satyakresna** [comment]
Hi @mamo5900 thanks for create this issue. I was forgot that I don't mention how to do that in docs. I just update the docs in section **API Usage - List of Omni Units**. Here, you can search omni units by name, element and both.

Example:

1. By `name` https://bravefrontier.satyakresna.io/api/v1/omniunits?name=war
2. By `element` https://bravefrontier.satyakresna.io/api/v1/omniunits?element=fire
3. By `name` and `element` https://bravefrontier.satyakresna.io/api/v1/omniunits?name=sun&element=fire

I hope it looks like what you expect. Thank you.

**Comment by mamo5900** [comment]
does the v2 work too?

**Comment by mamo5900** [comment]
> Hi @mamo5900 thanks for create this issue. I was forgot that I don't mention how to do that in docs. I just update the docs in section **API Usage - List of Omni Units**. Here, you can search omni units by name, element and both.
> 
> Example:
> 
> 1. By `name` https://bravefrontier.satyakresna.io/api/v1/omniunits?name=war
> 2. By `element` https://bravefrontier.satyakresna.io/api/v1/omniunits?element=fire
> 3. By `name` and `element` https://bravefrontier.satyakresna.io/api/v1/omniunits?name=sun&element=fire
> 
> I hope it looks like what you expect. Thank you.

if i search qiutong will show no results but i search qiuTong it show a record, can you fix or modify the files just for having the same result? also it happen when i search snow%20miku instead of Snow%20Miku

**Comment by satyakresna** [comment]
Hi @mamo5900, I just fix this issue by this commit 363c175. You can try it now.

**Note:** Please visit https://bfwiki.satyakresna.io to make you easier search and see detail of omni unit instead of using the https://bravefrontier.satyakresna.io.

**Comment by satyakresna** [comment]
I will close this issue.
